# Generated by Django 2.2.7 on 2019-12-20 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0003_auto_20191218_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password1',
        ),
    ]
